ALTER TABLE `legal_passages` ADD `keywords` text DEFAULT '' NOT NULL;
--> statement-breakpoint
ALTER TABLE `legal_passages` ADD `professional_summary` text;
--> statement-breakpoint
ALTER TABLE `legal_passages` ADD `plain_summary` text;
--> statement-breakpoint
UPDATE `legal_documents`
SET `review_status` = 'source_verified', `last_verified_at` = '2026-08-26', `updated_at` = CURRENT_TIMESTAMP
WHERE `id` = 'constitution-1999';
--> statement-breakpoint
INSERT INTO `legal_passages` (`id`,`document_id`,`provision_label`,`paragraph_number`,`text_content`,`keywords`,`professional_summary`,`plain_summary`,`checksum`,`review_status`) VALUES
('constitution-s1-1','constitution-1999','Section 1(1)','1','This Constitution is supreme and its provisions shall have binding force on all authorities and persons throughout the Federal Republic of Nigeria.','constitution supreme supremacy highest law binding force authorities persons','The Constitution is supreme and binds every authority and person throughout Nigeria.','The Constitution is Nigeria''s highest law, and everyone—including government authorities—must obey it.','constitution-s1-1-v1','source_verified'),
('constitution-s1-2','constitution-1999','Section 1(2)','2','The Federal Republic of Nigeria shall not be governed, nor shall any person or group of persons take control of the Government of Nigeria or any part thereof, except in accordance with the provisions of this Constitution.','government control govern constitution lawful takeover constitutional order','Nigeria may be governed, and governmental control may be assumed, only in accordance with the Constitution.','Nobody may govern Nigeria or take control of its government except in the way the Constitution permits.','constitution-s1-2-v1','source_verified'),
('constitution-s1-3','constitution-1999','Section 1(3)','3','If any other law is inconsistent with the provisions of this Constitution, this Constitution shall prevail, and that other law shall, to the extent of the inconsistency, be void.','constitution supreme supremacy conflict inconsistent law prevail void invalid','A law inconsistent with the Constitution is void to the extent of that inconsistency.','If another law conflicts with the Constitution, the Constitution wins and the conflicting part of that law has no legal effect.','constitution-s1-3-v1','source_verified'),
('constitution-s4-1','constitution-1999','Section 4(1)','1','The legislative powers of the Federal Republic of Nigeria shall be vested in a National Assembly for the Federation, which shall consist of a Senate and a House of Representatives.','legislative power make laws lawmaking national assembly senate house representatives federal','Federal legislative power is vested in the National Assembly, comprising the Senate and House of Representatives.','The National Assembly makes federal laws. It has two chambers: the Senate and the House of Representatives.','constitution-s4-1-v1','source_verified'),
('constitution-s4-2','constitution-1999','Section 4(2)','2','The National Assembly shall have power to make laws for the peace, order and good government of the Federation or any part thereof with respect to any matter included in the Exclusive Legislative List set out in Part I of the Second Schedule to this Constitution.','national assembly make laws peace order good government federation exclusive legislative list second schedule','The National Assembly may legislate for the Federation on matters in the Exclusive Legislative List.','The National Assembly can make laws on the federal subjects listed in the Constitution''s Exclusive Legislative List.','constitution-s4-2-v1','source_verified'),
('constitution-s4-3','constitution-1999','Section 4(3)','3','The power of the National Assembly to make laws for the peace, order and good government of the Federation with respect to any matter included in the Exclusive Legislative List shall, save as otherwise provided in this Constitution, be to the exclusion of the Houses of Assembly of States.','exclusive legislative list national assembly state house assembly exclusion powers federal laws','Except where the Constitution otherwise provides, legislative competence over Exclusive List matters belongs to the National Assembly and excludes State Houses of Assembly.','Generally, only the National Assembly may make laws about subjects on the Exclusive Legislative List; State Houses of Assembly cannot do so unless the Constitution allows it.','constitution-s4-3-v1','source_verified');
--> statement-breakpoint
PRAGMA optimize;
