export type ConstitutionPassage = {
  id: string;
  provisionLabel: string;
  pageNumber: number;
  paragraphNumber: string;
  textContent: string;
  keywords: string;
  professionalSummary: string;
  plainSummary: string;
};

export const constitutionPassages: ConstitutionPassage[] = [
  {
    id: "constitution-s1-1", provisionLabel: "Section 1(1)", pageNumber: 14, paragraphNumber: "1",
    textContent: "This Constitution is supreme and its provisions shall have binding force on all authorities and persons throughout the Federal Republic of Nigeria.",
    keywords: "constitution supreme supremacy highest law binding force authorities persons",
    professionalSummary: "The Constitution is supreme and binds every authority and person throughout Nigeria.",
    plainSummary: "The Constitution is Nigeria's highest law, and everyone—including government authorities—must obey it.",
  },
  {
    id: "constitution-s1-2", provisionLabel: "Section 1(2)", pageNumber: 14, paragraphNumber: "2",
    textContent: "The Federal Republic of Nigeria shall not be governed, nor shall any person or group of persons take control of the Government of Nigeria or any part thereof, except in accordance with the provisions of this Constitution.",
    keywords: "government control govern constitution lawful takeover constitutional order",
    professionalSummary: "Nigeria may be governed, and governmental control may be assumed, only in accordance with the Constitution.",
    plainSummary: "Nobody may govern Nigeria or take control of its government except in the way the Constitution permits.",
  },
  {
    id: "constitution-s1-3", provisionLabel: "Section 1(3)", pageNumber: 14, paragraphNumber: "3",
    textContent: "If any other law is inconsistent with the provisions of this Constitution, this Constitution shall prevail, and that other law shall to the extent of the inconsistency be void.",
    keywords: "constitution supreme supremacy conflict inconsistent law prevail void invalid",
    professionalSummary: "A law inconsistent with the Constitution is void to the extent of that inconsistency.",
    plainSummary: "If another law conflicts with the Constitution, the Constitution wins and the conflicting part of that law has no legal effect.",
  },
  {
    id: "constitution-s2-1", provisionLabel: "Section 2(1)", pageNumber: 14, paragraphNumber: "1",
    textContent: "Nigeria is one indivisible and indissoluble sovereign State to be known by the name of the Federal Republic of Nigeria.",
    keywords: "nigeria indivisible indissoluble sovereign state federal republic name",
    professionalSummary: "Nigeria is one indivisible and indissoluble sovereign State, named the Federal Republic of Nigeria.",
    plainSummary: "Nigeria is one country that cannot be split up. Its official name is the Federal Republic of Nigeria.",
  },
  {
    id: "constitution-s2-2", provisionLabel: "Section 2(2)", pageNumber: 14, paragraphNumber: "2",
    textContent: "Nigeria shall be a Federation consisting of States and a Federal Capital Territory.",
    keywords: "federation federal states federal capital territory fct abuja",
    professionalSummary: "Nigeria is a Federation of States and a Federal Capital Territory.",
    plainSummary: "Nigeria is a federation: it is made up of States plus a Federal Capital Territory.",
  },
  {
    id: "constitution-s3-1", provisionLabel: "Section 3(1)", pageNumber: 15, paragraphNumber: "1",
    textContent: "There shall be thirty six States in Nigeria, that is to say, Abia, Adamawa, Akwa Ibom, Anambra, Bauchi, Bayelsa, Benue, Borno, Cross River, Delta, Ebonyi, Edo, Ekiti, Enugu, Gombe, Imo, Jigawa, Kaduna, Kano, Katsina, Kebbi, Kogi, Kwara, Lagos, Nasarawa, Niger, Ogun, Ondo, Osun, Oyo, Plateau, Rivers, Sokoto, Taraba, Yobe and Zamfara.",
    keywords: "thirty six 36 states list abia lagos kano rivers abuja names of states",
    professionalSummary: "Nigeria consists of thirty-six named States.",
    plainSummary: "Nigeria has 36 States. Section 3(1) lists them by name.",
  },
  {
    id: "constitution-s3-2", provisionLabel: "Section 3(2)", pageNumber: 15, paragraphNumber: "2",
    textContent: "Each State of Nigeria named in the first column of Part I of the First Schedule to this Constitution shall consist of the area shown opposite thereto in the second column of that Schedule.",
    keywords: "state area territory first schedule part i boundaries",
    professionalSummary: "Each State's area is that shown opposite its name in Part I of the First Schedule.",
    plainSummary: "Each State's land area is the area written next to its name in the First Schedule.",
  },
  {
    id: "constitution-s3-3", provisionLabel: "Section 3(3)", pageNumber: 15, paragraphNumber: "3",
    textContent: "The headquarters of the Government of each State shall be known as the Capital City of that State as shown in the third column of the said Part I of the First Schedule opposite the State named in the first column thereof.",
    keywords: "capital city headquarters state government first schedule",
    professionalSummary: "Each State's capital city is that shown in the third column of Part I of the First Schedule.",
    plainSummary: "Each State has a capital city, named in the First Schedule.",
  },
  {
    id: "constitution-s3-4", provisionLabel: "Section 3(4)", pageNumber: 15, paragraphNumber: "4",
    textContent: "The Federal Capital Territory, Abuja shall be as defined in Part II of the First Schedule to this Constitution.",
    keywords: "federal capital territory abuja fct first schedule part ii",
    professionalSummary: "The Federal Capital Territory, Abuja is defined in Part II of the First Schedule.",
    plainSummary: "The Federal Capital Territory, Abuja is defined in the First Schedule to the Constitution.",
  },
  {
    id: "constitution-s3-5", provisionLabel: "Section 3(5)", pageNumber: 15, paragraphNumber: "5",
    textContent: "The provisions of this Constitution in Part I of Chapter VIII hereof shall, in relation to the Federal Capital Territory, Abuja, have effect in the manner set out thereunder.",
    keywords: "fct abuja chapter viii part i application constitution",
    professionalSummary: "Chapter VIII, Part I, applies to the FCT in the manner set out there.",
    plainSummary: "Special rules in Chapter VIII explain how the Constitution applies to Abuja, the Federal Capital Territory.",
  },
  {
    id: "constitution-s3-6", provisionLabel: "Section 3(6)", pageNumber: 15, paragraphNumber: "6",
    textContent: "There shall be seven hundred and sixty-eight local government areas in Nigeria as shown in the second column of Part I of the First Schedule to this Constitution and six area councils as shown in Part II of that Schedule.",
    keywords: "768 seven hundred sixty-eight local government areas area councils fct first schedule",
    professionalSummary: "Nigeria has 768 local government areas and six area councils as shown in the First Schedule.",
    plainSummary: "The Constitution records 768 local government areas and six area councils (in the FCT).",
  },
  {
    id: "constitution-s4-1", provisionLabel: "Section 4(1)", pageNumber: 15, paragraphNumber: "1",
    textContent: "The legislative powers of the Federal Republic of Nigeria shall be vested in a National Assembly for the Federation which shall consist of a Senate and a House of Representatives.",
    keywords: "legislative power make laws lawmaking national assembly senate house representatives federal",
    professionalSummary: "Federal legislative power is vested in the National Assembly, comprising the Senate and House of Representatives.",
    plainSummary: "The National Assembly makes federal laws. It has two chambers: the Senate and the House of Representatives.",
  },
  {
    id: "constitution-s4-2", provisionLabel: "Section 4(2)", pageNumber: 15, paragraphNumber: "2",
    textContent: "The National Assembly shall have power to make laws for the peace, order and good government of the Federation or any part thereof with respect to any matter included in the Exclusive Legislative List set out in Part I of the Second Schedule to this Constitution.",
    keywords: "national assembly make laws peace order good government federation exclusive legislative list second schedule",
    professionalSummary: "The National Assembly may legislate for the Federation on matters in the Exclusive Legislative List.",
    plainSummary: "The National Assembly can make laws on the federal subjects listed in the Constitution's Exclusive Legislative List.",
  },
  {
    id: "constitution-s4-3", provisionLabel: "Section 4(3)", pageNumber: 15, paragraphNumber: "3",
    textContent: "The power of the National Assembly to make laws for the peace, order and good government of the Federation with respect to any matter included in the Exclusive Legislative List shall, save as otherwise provided in this Constitution, be to the exclusion of the Houses of Assembly of States.",
    keywords: "exclusive legislative list national assembly state house assembly exclusion powers federal laws",
    professionalSummary: "Except where the Constitution otherwise provides, legislative competence over Exclusive List matters belongs to the National Assembly and excludes State Houses of Assembly.",
    plainSummary: "Generally, only the National Assembly may make laws about subjects on the Exclusive Legislative List; State Houses of Assembly cannot do so unless the Constitution allows it.",
  },
  {
    id: "constitution-s4-4", provisionLabel: "Section 4(4)", pageNumber: 16, paragraphNumber: "4",
    textContent: "In addition and without prejudice to the powers conferred by subsection (2) of this section, the National Assembly shall have power to make laws with respect to the following matters, that is to say— (a) any matter in the Concurrent Legislative List set out in the first column of Part II of the Second Schedule to this Constitution to the extent prescribed in the second column opposite thereto; and (b) any other matter with respect to which it is empowered to make laws in accordance with the provisions of this Constitution.",
    keywords: "concurrent legislative list national assembly additional legislative power second schedule",
    professionalSummary: "The National Assembly may also legislate on Concurrent List matters to the extent prescribed, and on any other matter it is constitutionally empowered to legislate upon.",
    plainSummary: "The National Assembly can also make laws on shared (concurrent) subjects, to the extent the Constitution allows, and on any other subject the Constitution gives it.",
  },
  {
    id: "constitution-s4-5", provisionLabel: "Section 4(5)", pageNumber: 16, paragraphNumber: "5",
    textContent: "If any Law enacted by the House of Assembly of a State is inconsistent with any law validly made by the National Assembly, the law made by the National Assembly shall prevail, and that other Law shall to the extent of the inconsistency be void.",
    keywords: "inconsistent state law national assembly prevail void conflict supremacy federal statute",
    professionalSummary: "A valid National Assembly law prevails over an inconsistent State House of Assembly law, which is void to the extent of the inconsistency.",
    plainSummary: "If a State law conflicts with a valid federal law, the federal law wins and the conflicting part of the State law has no effect.",
  },
  {
    id: "constitution-s4-6", provisionLabel: "Section 4(6)", pageNumber: 16, paragraphNumber: "6",
    textContent: "The legislative powers of a State of the Federation shall be vested in the House of Assembly of the State.",
    keywords: "state legislative power house of assembly state lawmaking",
    professionalSummary: "State legislative power is vested in the House of Assembly of that State.",
    plainSummary: "Each State's House of Assembly makes that State's laws.",
  },
  {
    id: "constitution-s4-7", provisionLabel: "Section 4(7)", pageNumber: 16, paragraphNumber: "7",
    textContent: "The House of Assembly of a State shall have power to make laws for the peace, order and good government of the State or any part thereof with respect to the following matters, that is to say— (a) any matter not included in the Exclusive Legislative List set out in Part I of the Second Schedule to this Constitution; (b) any matter included in the Concurrent Legislative List set out in the first column of Part II of the Second Schedule to this Constitution to the extent prescribed in the second column opposite thereto; and (c) any other matter with respect to which it is empowered to make laws in accordance with the provisions of this Constitution.",
    keywords: "state house assembly residual matters concurrent list exclusive list state laws",
    professionalSummary: "A State House of Assembly may legislate on matters not on the Exclusive List, on Concurrent List matters to the prescribed extent, and on any other matter the Constitution empowers it to legislate upon.",
    plainSummary: "A State House of Assembly can make laws on subjects that are not exclusive to the National Assembly, on shared subjects to the allowed extent, and on anything else the Constitution gives it.",
  },
  {
    id: "constitution-s4-8", provisionLabel: "Section 4(8)", pageNumber: 16, paragraphNumber: "8",
    textContent: "Save as otherwise provided by this Constitution, the exercise of legislative powers by the National Assembly or by a House of Assembly shall be subject to the jurisdiction of courts of law and of judicial tribunals established by law, and accordingly, the National Assembly or a House of Assembly shall not enact any law that ousts or purports to oust the jurisdiction of a court of law or of a judicial tribunal established by law.",
    keywords: "oust jurisdiction courts tribunals legislative powers judicial review ouster clause",
    professionalSummary: "Legislative power is subject to the courts. Neither the National Assembly nor a House of Assembly may enact a law ousting the jurisdiction of a court or lawfully established judicial tribunal.",
    plainSummary: "Lawmakers cannot pass a law that stops the courts from hearing a case, unless the Constitution itself says otherwise.",
  },
  {
    id: "constitution-s4-9", provisionLabel: "Section 4(9)", pageNumber: 16, paragraphNumber: "9",
    textContent: "Notwithstanding the foregoing provisions of this section, the National Assembly or a House of Assembly shall not, in relation to any criminal offence whatsoever, have power to make any law which shall have retrospective effect.",
    keywords: "retrospective retroactive criminal offence national assembly house of assembly ex post facto",
    professionalSummary: "Neither the National Assembly nor a House of Assembly may make a retrospective criminal law.",
    plainSummary: "Parliament cannot make a crime out of something after it has already happened, or punish it more severely after the fact.",
  },
  {
    id: "constitution-s5-1", provisionLabel: "Section 5(1)", pageNumber: 16, paragraphNumber: "1",
    textContent: "Subject to the provisions of this Constitution, the executive powers of the Federation— (a) shall be vested in the President and may, subject as aforesaid and to the provisions of any law made by the National Assembly, be exercised by him either directly or through the Vice-President and Ministers of the Government of the Federation or officers in the public service of the Federation; and (b) shall extend to the execution and maintenance of this Constitution, all laws made by the National Assembly and to all matters with respect to which the National Assembly has, for the time being, power to make laws.",
    keywords: "executive powers president vice-president ministers federation public service",
    professionalSummary: "Federal executive power is vested in the President, exercisable directly or through the Vice-President, Ministers, or federal public officers, and extends to executing the Constitution and federal laws.",
    plainSummary: "The President holds federal executive power and may use it personally or through the Vice-President, Ministers, and federal officers. That power includes carrying out the Constitution and federal laws.",
  },
  {
    id: "constitution-s5-2", provisionLabel: "Section 5(2)", pageNumber: 17, paragraphNumber: "2",
    textContent: "Subject to the provisions of this Constitution, the executive powers of a State— (a) shall be vested in the Governor of that State and may, subject as aforesaid and to the provisions of any Law made by a House of Assembly, be exercised by him either directly or through the Deputy Governor and Commissioners of the Government of that State or officers in the public service of the State; and (b) shall extend to the execution and maintenance of this Constitution, all laws made by the House of Assembly of the State and to all matters with respect to which the House of Assembly has for the time being power to make laws.",
    keywords: "executive powers governor deputy governor commissioners state public service",
    professionalSummary: "State executive power is vested in the Governor, exercisable directly or through the Deputy Governor, Commissioners, or State public officers.",
    plainSummary: "The Governor holds a State's executive power and may use it personally or through the Deputy Governor, Commissioners, and State officers.",
  },
  {
    id: "constitution-s5-3", provisionLabel: "Section 5(3)", pageNumber: 17, paragraphNumber: "3",
    textContent: "The executive powers vested in a State under subsection (2) of this section shall be so exercised as not to— (a) impede or prejudice the exercise of the executive powers of the Federation; (b) endanger any asset or investment of the Government of the Federation in that State; or (c) endanger the continuance of a federal government in Nigeria.",
    keywords: "state executive limits impede federal powers assets investment federal government",
    professionalSummary: "A State must not exercise its executive powers so as to impede federal executive power, endanger federal assets in the State, or endanger continuance of a federal government in Nigeria.",
    plainSummary: "A State government must not use its powers in a way that blocks the federal government, puts federal property in danger, or threatens Nigeria remaining a federation.",
  },
  {
    id: "constitution-s5-4", provisionLabel: "Section 5(4)", pageNumber: 17, paragraphNumber: "4",
    textContent: "Notwithstanding the foregoing provisions of this section— (a) the President shall not declare a state of war between the Federation and another country except with the sanction of a resolution of both Houses of the National Assembly sitting in a joint session; and (b) except with the prior approval of the Senate, no member of the armed forces of the Federation shall be deployed on combat duty outside Nigeria.",
    keywords: "war declaration national assembly joint session senate armed forces combat duty outside nigeria",
    professionalSummary: "A declaration of war requires a joint-session resolution of both Houses. Combat deployment of armed forces outside Nigeria requires prior Senate approval, subject to section 5(5).",
    plainSummary: "The President cannot declare war unless both Houses of the National Assembly, sitting together, agree. Sending soldiers to fight outside Nigeria normally needs the Senate's prior approval.",
  },
  {
    id: "constitution-s5-5", provisionLabel: "Section 5(5)", pageNumber: 17, paragraphNumber: "5",
    textContent: "Notwithstanding the provisions of subsection (4) of this section, the President, in consultation with the National Defence Council, may deploy members of the armed forces of the Federation on a limited combat duty outside Nigeria if he is satisfied that the national interest is under imminent threat or danger: Provided that the President shall, within seven days of actual combat engagement, seek the consent of the Senate and the Senate shall thereafter give or refuse the said consent within fourteen days.",
    keywords: "limited combat duty outside nigeria national defence council imminent threat senate consent seven days fourteen days",
    professionalSummary: "The President may, after consulting the National Defence Council, deploy forces on limited combat duty outside Nigeria where national interest is under imminent threat, but must seek Senate consent within seven days of actual combat engagement; the Senate has fourteen days to give or refuse consent.",
    plainSummary: "If Nigeria is in immediate danger, the President may, after consulting the National Defence Council, send forces on limited combat duty abroad, but must ask the Senate for approval within seven days of actual fighting. The Senate then has fourteen days to say yes or no.",
  },
  {
    id: "constitution-s6-1", provisionLabel: "Section 6(1)", pageNumber: 17, paragraphNumber: "1",
    textContent: "The judicial powers of the Federation shall be vested in the courts to which this section relates, being courts established for the Federation.",
    keywords: "judicial powers federation federal courts",
    professionalSummary: "Federal judicial power is vested in the courts to which section 6 relates that are established for the Federation.",
    plainSummary: "Federal judicial power belongs to the federal courts named in section 6.",
  },
  {
    id: "constitution-s6-2", provisionLabel: "Section 6(2)", pageNumber: 17, paragraphNumber: "2",
    textContent: "The judicial powers of a State shall be vested in the courts to which this section relates, being courts established, subject as provided by this Constitution, for a State.",
    keywords: "judicial powers state courts",
    professionalSummary: "State judicial power is vested in the courts to which section 6 relates that are established for a State.",
    plainSummary: "State judicial power belongs to the State courts named in section 6.",
  },
  {
    id: "constitution-s6-3", provisionLabel: "Section 6(3)", pageNumber: 17, paragraphNumber: "3",
    textContent: "The courts to which this section relates, established by this Constitution for the Federation and for the States, specified in subsection (5) (a) to (i) of this section, shall be the only superior courts of record in Nigeria; and save as otherwise prescribed by the National Assembly or by the House of Assembly of a State, each court shall have all the powers of a superior court of record.",
    keywords: "superior courts of record subsection 5 supreme court court of appeal high court",
    professionalSummary: "The courts listed in section 6(5)(a)–(i) are the only superior courts of record in Nigeria, and each has the powers of a superior court of record unless otherwise prescribed by law.",
    plainSummary: "The courts listed in section 6(5)(a) to (i) are Nigeria's only superior courts of record. Unless a law says otherwise, each of them has the full powers of such a court.",
  },
  {
    id: "constitution-s6-4", provisionLabel: "Section 6(4)", pageNumber: 18, paragraphNumber: "4",
    textContent: "Nothing in the foregoing provisions of this section shall be construed as precluding— (a) the National Assembly or any House of Assembly from establishing courts, other than those to which this section relates, with subordinate jurisdiction to that of a High Court; (b) the National Assembly or any House of Assembly, which does not require it, from abolishing any court which it has power to establish or which it has brought into being.",
    keywords: "establish courts abolish subordinate jurisdiction high court magistrate",
    professionalSummary: "The National Assembly or a House of Assembly may establish courts subordinate to a High Court, and may abolish a court it has power to establish or has brought into being.",
    plainSummary: "Lawmakers can create lower courts beneath the High Court, and can abolish a court they have the power to create.",
  },
  {
    id: "constitution-s6-5", provisionLabel: "Section 6(5)", pageNumber: 18, paragraphNumber: "5",
    textContent: "This section relates to— (a) the Supreme Court of Nigeria; (b) the Court of Appeal; (c) the Federal High Court; (d) the High Court of the Federal Capital Territory, Abuja; (e) a High Court of a State; (f) the Sharia Court of Appeal of the Federal Capital Territory, Abuja; (g) a Sharia Court of Appeal of a State; (h) the Customary Court of Appeal of the Federal Capital Territory, Abuja; (i) a Customary Court of Appeal of a State; (j) such other courts as may be authorised by law to exercise jurisdiction on matters with respect to which the National Assembly may make laws; and (k) such other courts as may be authorised by law to exercise jurisdiction at first instance or on appeal on matters with respect to which a House of Assembly may make laws.",
    keywords: "supreme court court of appeal federal high court high court sharia court of appeal customary court of appeal superior courts list",
    professionalSummary: "Section 6 relates to the Supreme Court, Court of Appeal, Federal High Court, High Courts, Sharia Courts of Appeal, Customary Courts of Appeal, and other courts authorised by law.",
    plainSummary: "The courts this section is about include the Supreme Court, Court of Appeal, Federal High Court, State and FCT High Courts, Sharia Courts of Appeal, Customary Courts of Appeal, and other courts a law may create.",
  },
  {
    id: "constitution-s6-6", provisionLabel: "Section 6(6)", pageNumber: 18, paragraphNumber: "6",
    textContent: "The judicial powers vested in accordance with the foregoing provisions of this section— (a) shall extend, notwithstanding anything to the contrary in this Constitution, to all inherent powers and sanctions of a court of law; (b) shall extend to all matters between persons, or between government or authority and to any person in Nigeria, and to all actions and proceedings relating thereto, for the determination of any question as to the civil rights and obligations of that person; (c) shall not, except as otherwise provided by this Constitution, extend to any issue or question as to whether any act or omission by any authority or person or as to whether any law or any judicial decision is in conformity with the Fundamental Objectives and Directive Principles of State Policy set out in Chapter II of this Constitution; and (d) shall not, as from the date when this section comes into force, extend to any action or proceedings relating to any existing law made on or after 15 January 1966 for determining any issue or question as to the competence of any authority or person to make any such law.",
    keywords: "inherent powers civil rights obligations chapter ii directive principles justiciability 15 january 1966",
    professionalSummary: "Judicial powers include inherent court powers and civil-rights disputes, but generally do not extend to whether a matter conforms to Chapter II, nor to specified post-15 January 1966 competence challenges.",
    plainSummary: "Courts can use the ordinary powers of a court of law and can decide disputes about people's civil rights. They generally cannot be asked whether government has complied with Chapter II (the policy goals in the Constitution), unless another part of the Constitution allows it.",
  },
  {
    id: "constitution-s7-1", provisionLabel: "Section 7(1)", pageNumber: 18, paragraphNumber: "1",
    textContent: "The system of local government by democratically elected local government councils is under this Constitution guaranteed; and accordingly, the Government of every State shall, subject to section 8 of this Constitution, ensure their existence under a Law which provides for the establishment, structure, composition, finance and functions of such councils.",
    keywords: "local government democratically elected councils guaranteed state law establishment finance functions",
    professionalSummary: "Democratically elected local government councils are constitutionally guaranteed. Every State must, subject to section 8, ensure their existence under a Law covering establishment, structure, composition, finance and functions.",
    plainSummary: "The Constitution guarantees elected local government councils. Each State must have a law that sets up those councils and deals with their structure, membership, money, and functions.",
  },
  {
    id: "constitution-s7-2", provisionLabel: "Section 7(2)", pageNumber: 19, paragraphNumber: "2",
    textContent: "The person authorised by law to prescribe the area over which a local government council may exercise authority shall— (a) define such area as clearly as practicable; and (b) ensure, to the extent to which it may be reasonably justifiable, that in defining such area regard is paid to— (i) the common interest of the community in the area; (ii) traditional association of the community; and (iii) administrative convenience.",
    keywords: "local government area prescribe community interest traditional association administrative convenience",
    professionalSummary: "The person authorised to prescribe a local government area must define it clearly and, so far as reasonably justifiable, have regard to common interest, traditional association, and administrative convenience.",
    plainSummary: "When drawing a local government area, the law requires a clear boundary and, as far as reasonable, attention to the community's common interest, traditional ties, and ease of administration.",
  },
  {
    id: "constitution-s7-3", provisionLabel: "Section 7(3)", pageNumber: 19, paragraphNumber: "3",
    textContent: "It shall be the duty of a local government council within the State to participate in economic planning and development of the area referred to in subsection (2) of this section and to this end an economic planning board shall be established by a Law enacted by the House of Assembly of the State.",
    keywords: "local government economic planning development board house of assembly",
    professionalSummary: "A local government council must participate in economic planning and development of its area; a State House of Assembly Law shall establish an economic planning board for that purpose.",
    plainSummary: "Local governments must take part in planning the economy of their area. The State House of Assembly is to set up an economic planning board by law.",
  },
  {
    id: "constitution-s7-4", provisionLabel: "Section 7(4)", pageNumber: 19, paragraphNumber: "4",
    textContent: "The Government of a State shall ensure that every person who is entitled to vote or be voted for at an election to a House of Assembly shall have the right to vote or be voted for at an election to a local government council.",
    keywords: "local government election vote franchise house of assembly",
    professionalSummary: "Anyone entitled to vote or be voted for at a House of Assembly election has the corresponding right at a local government council election.",
    plainSummary: "If you can vote or stand in a State House of Assembly election, you can also vote or stand in a local government election.",
  },
  {
    id: "constitution-s7-5", provisionLabel: "Section 7(5)", pageNumber: 19, paragraphNumber: "5",
    textContent: "The functions to be conferred by Law upon local government councils shall include those set out in the Fourth Schedule to this Constitution.",
    keywords: "local government functions fourth schedule",
    professionalSummary: "Functions conferred by Law on local government councils must include those in the Fourth Schedule.",
    plainSummary: "State law on local government functions must include the functions listed in the Fourth Schedule to the Constitution.",
  },
  {
    id: "constitution-s7-6", provisionLabel: "Section 7(6)", pageNumber: 19, paragraphNumber: "6",
    textContent: "Subject to the provisions of this Constitution— (a) the National Assembly shall make provisions for statutory allocation of public revenue to local government councils in the Federation; and (b) the House of Assembly of a State shall make provisions for statutory allocation of public revenue to local government councils within the State.",
    keywords: "statutory allocation public revenue local government councils national assembly house of assembly",
    professionalSummary: "The National Assembly provides for statutory allocation of public revenue to local government councils in the Federation; a State House of Assembly does so for councils within the State.",
    plainSummary: "The National Assembly must provide for sharing public money to local governments nationwide. Each State House of Assembly must provide for sharing public money to local governments in that State.",
  },
  {
    id: "constitution-s8-1", provisionLabel: "Section 8(1)", pageNumber: 19, paragraphNumber: "1",
    textContent: "An Act of the National Assembly for the purpose of creating a new State shall only be passed if— (a) a request, supported by at least two-thirds majority of members (representing the area demanding the creation of the new State) in each of the following, namely— (i) the Senate and the House of Representatives; (ii) the House of Assembly in respect of the area; and (iii) the local government councils in respect of the area, is received by the National Assembly; (b) a proposal for the creation of the State is thereafter approved in a referendum by at least two-thirds majority of the people of the area where the demand for creation of the State originated; (c) the result of the referendum is then approved by a simple majority of all the States of the Federation supported by a simple majority of members of the Houses of Assembly; and (d) the proposal is approved by a resolution passed by two-thirds majority of members of each House of the National Assembly.",
    keywords: "create new state referendum two-thirds national assembly senate house of representatives local government",
    professionalSummary: "Creating a new State requires a supported request from specified bodies, a two-thirds referendum in the area, majority approval of the States supported by Houses of Assembly, and a two-thirds resolution of each House of the National Assembly.",
    plainSummary: "A new State can be created only after several high thresholds: support from legislators and local councils in the area, a two-thirds referendum there, majority support among the States, and a two-thirds vote in each House of the National Assembly.",
  },
  {
    id: "constitution-s8-2", provisionLabel: "Section 8(2)", pageNumber: 20, paragraphNumber: "2",
    textContent: "An Act of the National Assembly for the purpose of boundary adjustment of any existing State shall only be passed if— (a) a request for the boundary adjustment, supported by two-thirds majority of members (representing the area demanding and the area affected by the boundary adjustment) in each of the following, namely— (i) the Senate and the House of Representatives; (ii) the House of Assembly in respect of the area; and (iii) the local government councils in respect of the area, is received by the National Assembly; and (b) a proposal for the boundary adjustment is approved by— (i) a simple majority of members of each House of the National Assembly; and (ii) a simple majority of members of the House of Assembly in respect of the area concerned.",
    keywords: "boundary adjustment state two-thirds request simple majority national assembly",
    professionalSummary: "State boundary adjustment requires a two-thirds supported request from specified bodies and simple-majority approval in each House of the National Assembly and in the House of Assembly for the area.",
    plainSummary: "Changing a State's boundary is a defined process: a strongly supported request from the area, then simple majority votes in the National Assembly and in the relevant State House of Assembly.",
  },
  {
    id: "constitution-s8-3", provisionLabel: "Section 8(3)", pageNumber: 20, paragraphNumber: "3",
    textContent: "A bill for a Law of a House of Assembly for the purpose of creating a new local government area shall only be passed if— (a) a request supported by at least two-thirds majority of members (representing the area demanding the creation of the new local government area) in each of the following, namely— (i) the House of Assembly in respect of the area; and (ii) the local government councils in respect of the area, is received by the House of Assembly; (b) a proposal for the creation of the local government area is thereafter approved in a referendum by at least two-thirds majority of the people of the local government area where the demand for the proposed local government area originated; (c) the result of the referendum is then approved by a simple majority of the members in each local government council in a majority of all the local government councils in the State; and (d) the result of the referendum is approved by a resolution passed by two-thirds majority of members of the House of Assembly.",
    keywords: "create new local government area referendum house of assembly two-thirds",
    professionalSummary: "Creating a new local government area requires a supported request, a two-thirds local referendum, specified council approvals, and a two-thirds House of Assembly resolution.",
    plainSummary: "A new local government area can be created only after local support, a two-thirds referendum, further council approvals, and a two-thirds vote in the State House of Assembly.",
  },
  {
    id: "constitution-s8-4", provisionLabel: "Section 8(4)", pageNumber: 20, paragraphNumber: "4",
    textContent: "A bill for a Law of a House of Assembly for the purpose of boundary adjustment of any existing local government area shall only be passed if— (a) a request for the boundary adjustment is supported by two-thirds majority of members (representing the area demanding and the area affected by the boundary adjustment) in each of the following, namely— (i) the House of Assembly in respect of the area; and (ii) the local government council in respect of the area, is received by the House of Assembly; and (b) a proposal for the boundary adjustment is approved by a simple majority of members of the House of Assembly in respect of the area concerned.",
    keywords: "local government boundary adjustment house of assembly two-thirds",
    professionalSummary: "Adjusting a local government boundary requires a two-thirds supported request from specified bodies and simple-majority approval of the House of Assembly for the area.",
    plainSummary: "Changing a local government boundary needs a strongly supported request from the area and then a simple majority in the State House of Assembly.",
  },
  {
    id: "constitution-s8-5", provisionLabel: "Section 8(5)", pageNumber: 21, paragraphNumber: "5",
    textContent: "An Act of the National Assembly passed in accordance with this section shall make consequential provisions with respect to the names and headquarters of States or local government areas as provided in section 3 of this Constitution and in Parts I and II of the First Schedule to this Constitution.",
    keywords: "consequential provisions names headquarters first schedule section 3",
    professionalSummary: "A National Assembly Act passed under section 8 must make consequential provision for names and headquarters of States or local government areas as in section 3 and the First Schedule.",
    plainSummary: "If the National Assembly creates or changes States or local governments under section 8, the Act must also update their names and headquarters in line with section 3 and the First Schedule.",
  },
  {
    id: "constitution-s8-6", provisionLabel: "Section 8(6)", pageNumber: 21, paragraphNumber: "6",
    textContent: "For the purpose of enabling the National Assembly to exercise the powers conferred upon it by subsection (5) of this section, each House of Assembly shall, after the creation of more local government areas pursuant to subsection (3) of this section, make adequate returns to each House of the National Assembly.",
    keywords: "returns house of assembly national assembly new local government areas",
    professionalSummary: "After creating more local government areas under subsection (3), each House of Assembly must make adequate returns to each House of the National Assembly.",
    plainSummary: "If a State creates more local government areas, its House of Assembly must send proper returns to the National Assembly so the federal records can be updated.",
  },
  {
    id: "constitution-s9-1", provisionLabel: "Section 9(1)", pageNumber: 21, paragraphNumber: "1",
    textContent: "The National Assembly may, subject to the provisions of this section, alter any of the provisions of this Constitution.",
    keywords: "alter amendment constitution national assembly",
    professionalSummary: "The National Assembly may alter the Constitution, subject to section 9.",
    plainSummary: "The National Assembly can change the Constitution, but only by following the special rules in section 9.",
  },
  {
    id: "constitution-s9-2", provisionLabel: "Section 9(2)", pageNumber: 21, paragraphNumber: "2",
    textContent: "An Act of the National Assembly for the alteration of this Constitution, not being an Act to which section 8 of this Constitution applies, shall not be passed in either House of the National Assembly unless the proposal is supported by the votes of not less than two-thirds majority of all the members of that House and approved by resolution of the Houses of Assembly of not less than two-thirds of all the States.",
    keywords: "alter constitution two-thirds national assembly houses of assembly states amendment",
    professionalSummary: "A constitutional alteration (other than a section 8 Act) requires two-thirds of all members of each House of the National Assembly and approval by resolution of the Houses of Assembly of at least two-thirds of all the States.",
    plainSummary: "Changing most parts of the Constitution needs two-thirds of all members in each federal chamber, plus approval from the Houses of Assembly of at least two-thirds of the States.",
  },
  {
    id: "constitution-s9-3", provisionLabel: "Section 9(3)", pageNumber: 21, paragraphNumber: "3",
    textContent: "An Act of the National Assembly for the purpose of altering the provisions of this section, section 8 or Chapter IV of this Constitution shall not be passed by either House of the National Assembly unless the proposal is approved by the votes of not less than four-fifths majority of all the members of each House, and also approved by resolution of the Houses of Assembly of not less than two-thirds of all the States.",
    keywords: "four-fifths chapter iv fundamental rights section 8 section 9 special amendment",
    professionalSummary: "Altering section 9, section 8, or Chapter IV requires four-fifths of all members of each House of the National Assembly and approval by resolution of the Houses of Assembly of at least two-thirds of all the States.",
    plainSummary: "Changing the amendment rules themselves, the rules for new States, or the fundamental rights chapter is harder: four-fifths of each federal chamber, plus approval from Houses of Assembly of at least two-thirds of the States.",
  },
  {
    id: "constitution-s9-4", provisionLabel: "Section 9(4)", pageNumber: 21, paragraphNumber: "4",
    textContent: "For the purposes of section 8 of this Constitution and of subsections (2) and (3) of this section, the number of members of each House of the National Assembly shall, notwithstanding any vacancy, be deemed to be the number of members specified in sections 48 and 49 of this Constitution.",
    keywords: "vacancy two-thirds four-fifths sections 48 49 membership national assembly",
    professionalSummary: "Vacancies do not reduce the denominator: membership of each House is deemed the number specified in sections 48 and 49.",
    plainSummary: "Empty seats do not make it easier to pass these special votes. The total is the full number of seats in sections 48 and 49.",
  },
  {
    id: "constitution-s10", provisionLabel: "Section 10", pageNumber: 21, paragraphNumber: "1",
    textContent: "The Government of the Federation or of a State shall not adopt any religion as State Religion.",
    keywords: "state religion secular prohibition federation state government adopt religion",
    professionalSummary: "Neither the Federation nor a State may adopt any religion as State Religion.",
    plainSummary: "The federal government and State governments must not make any religion the official State religion.",
  },
  {
    id: "constitution-s11-1", provisionLabel: "Section 11(1)", pageNumber: 21, paragraphNumber: "1",
    textContent: "The National Assembly may make laws for the Federation or any part thereof with respect to the maintenance and securing of public safety and public order and providing, maintaining and securing of such supplies and services as may be designated by the National Assembly as essential supplies and services.",
    keywords: "public safety public order essential supplies services national assembly emergency",
    professionalSummary: "The National Assembly may legislate on public safety and public order, and on supplies and services it designates as essential.",
    plainSummary: "The National Assembly can make laws about public safety and public order, and about supplies and services it calls essential.",
  },
  {
    id: "constitution-s11-2", provisionLabel: "Section 11(2)", pageNumber: 21, paragraphNumber: "2",
    textContent: "Nothing in this section shall preclude a House of Assembly from making laws with respect to the matters referred to in this section, including the provision for maintenance and securing of such supplies and services as may be designated by the National Assembly as essential supplies and services.",
    keywords: "house of assembly public order essential supplies concurrent",
    professionalSummary: "A House of Assembly is not precluded from legislating on the same public-order and essential-supplies matters.",
    plainSummary: "State Houses of Assembly can also make laws on these public-order and essential-supplies subjects.",
  },
  {
    id: "constitution-s11-3", provisionLabel: "Section 11(3)", pageNumber: 22, paragraphNumber: "3",
    textContent: "During any period when the Federation is at war the National Assembly may make such laws for the peace, order and good government of the Federation or any part thereof with respect to matters not included in the Exclusive Legislative List as may appear to it to be necessary or expedient for the defence of the Federation.",
    keywords: "war defence national assembly exclusive list peace order good government",
    professionalSummary: "While the Federation is at war, the National Assembly may legislate even on non-Exclusive List matters as appears necessary or expedient for defence.",
    plainSummary: "If Nigeria is at war, the National Assembly may make extra laws, even on subjects that are not normally exclusive federal subjects, if needed for defence.",
  },
  {
    id: "constitution-s11-4", provisionLabel: "Section 11(4)", pageNumber: 22, paragraphNumber: "4",
    textContent: "At any time when any House of Assembly of a State is unable to perform its functions by reason of the situation prevailing in that State, the National Assembly may make such laws for the peace, order and good government of that State with respect to matters on which a House of Assembly may make laws as may appear to the National Assembly to be necessary or expedient until such time as the House of Assembly is able to resume its functions; and any such laws enacted by the National Assembly shall have effect as if they were laws enacted by the House of Assembly of the State: Provided that nothing in this section shall be construed as conferring on the National Assembly power to remove the Governor or the Deputy Governor of the State from office.",
    keywords: "house of assembly unable perform functions national assembly state laws governor deputy governor",
    professionalSummary: "If a House of Assembly cannot perform its functions because of the situation in the State, the National Assembly may temporarily legislate on State matters for that State, but this does not authorise removal of the Governor or Deputy Governor.",
    plainSummary: "If a State House of Assembly cannot function because of the situation in the State, the National Assembly may temporarily make that State's laws. It still cannot use this section to remove the Governor or Deputy Governor.",
  },
  {
    id: "constitution-s11-5", provisionLabel: "Section 11(5)", pageNumber: 22, paragraphNumber: "5",
    textContent: "For the purposes of subsection (4) of this section, a House of Assembly shall not be deemed to be unable to perform its functions so long as the House of Assembly can hold a meeting and transact business.",
    keywords: "unable perform functions hold meeting transact business house of assembly",
    professionalSummary: "A House of Assembly is not deemed unable to perform its functions while it can hold a meeting and transact business.",
    plainSummary: "If the House of Assembly can still meet and do business, it is not treated as unable to function under section 11(4).",
  },
  {
    id: "constitution-s12-1", provisionLabel: "Section 12(1)", pageNumber: 22, paragraphNumber: "1",
    textContent: "No treaty between the Federation and any other country shall have the force of law except to the extent to which any such treaty has been enacted into law by the National Assembly.",
    keywords: "treaty force of law enacted national assembly international agreement dualist",
    professionalSummary: "A treaty has the force of law in Nigeria only to the extent it has been enacted into law by the National Assembly.",
    plainSummary: "An international treaty is not automatically Nigerian law. It has legal force here only to the extent the National Assembly has turned it into a Nigerian law.",
  },
  {
    id: "constitution-s12-2", provisionLabel: "Section 12(2)", pageNumber: 22, paragraphNumber: "2",
    textContent: "The National Assembly may make laws for the Federation or any part thereof with respect to matters not included in the Exclusive Legislative List for the purpose of implementing a treaty.",
    keywords: "implementing treaty exclusive list national assembly",
    professionalSummary: "The National Assembly may legislate even on non-Exclusive List matters for the purpose of implementing a treaty.",
    plainSummary: "To implement a treaty, the National Assembly may make laws even on subjects that are not on the Exclusive Legislative List.",
  },
  {
    id: "constitution-s12-3", provisionLabel: "Section 12(3)", pageNumber: 22, paragraphNumber: "3",
    textContent: "A bill for an Act of the National Assembly passed pursuant to the provisions of subsection (2) of this section shall not be presented to the President for assent, and shall not be enacted unless it is ratified by a majority of all the Houses of Assembly in the Federation.",
    keywords: "treaty implementing bill president assent ratified houses of assembly majority",
    professionalSummary: "A bill under section 12(2) cannot be presented for presidential assent or enacted unless ratified by a majority of all the Houses of Assembly.",
    plainSummary: "If the National Assembly uses section 12(2) to implement a treaty on a non-exclusive subject, a majority of all State Houses of Assembly must ratify the bill before it can become law.",
  },
];
